### ISSUE TITLE
invalid locale name: "Russian_Russia.1251"

### ISSUE THREAD

**Issue by antonkalinin-ml** [paffel2/testdb#5]
Запустил сервер, вызвал скрипт `./sh/initDb.sh` . Выдается ошибка:

```
invalid locale name: "Russian_Russia.1251"
```

Лог следующий:

```
Info| Server started
Info| Preparing data creating database
Debug| Creating connection
Debug| Creating pool
Debug| Read script
Debug| Script readed and translated to query
Debug| Start creating
Error| invalid locale name: "Russian_Russia.1251"
Error| Database not created
```

Система Debian 11.0, локаль `ru_RU.CP1251` в системе есть. Postgresql 13.0. Быстро полечить это у меня не получилось, есть идеи? Хочется проект запустить.

**Comment by paffel2** [comment]
если только локаль менять в sql/init_database.sql

**Comment by paffel2** [comment]
Но у меня винда, тоже как то не выходит. С тем что есть работает нормально.

**Comment by paffel2** [comment]
Промучавшись с wsl и дебианом, все таки запустил запустил. Единственно, так и не разобрался как подключить русскую локаль.

**Comment by olgaklimenko** [comment]
А как сделать чтобы у нас тоже запустилось?

**Comment by paffel2** [comment]
Для запуска на линуксе, я сделал отдельный скрипт и проверку системы. Завел на эту тему pull request.
